### ISSUE TITLE
AOSP support for Xperia L3 I4312

### ISSUE THREAD

**Issue by zlianon** [sonyxperiadev/device-sony-common#777]

**Comment by Paulbouchara** [comment]
This device is a mediatek device hence it's not supported on SODP

**Comment by Haxk20** [comment]
As Paul said. The device has Mediatek SoC and thus we cant support it.

**Comment by MartinX3** [comment]
Like Hax mentioned, we only support snapdragon xperias at the moment.

**Comment by zlianon** [comment]
@Paulbouchara @Haxk20 @MartinX3 

Sony Xperia L2 it's mediatek device, but it's on the list to unlock bootloader
https://developer.sony.com/develop/open-devices/get-started/unlock-bootloader/

I checked if it is possibly to unlock bootloader on my device I4312 via *#*#7378423#*#*, and yes, it's possible, but I can't unlock via developer options or https://developer.sony.com/develop/open-devices/get-started/unlock-bootloader/how-to-unlock-bootloader/ guide, any suggestions?

Thanks, and sorry for my bad English.

**Comment by Haxk20** [comment]
@zlianon Nearly every device from SONY is able to unlock bootloader. The issue isnt that you cant unlock bootloader. The issue is that the SoC manufacturer (Mediatek) isnt really known for providing support for Open Source community.

If we dont get base kernel for the SoC then we really cant do anything.
We are sorry but this is completely out of our hands.

**Comment by MartinX3** [comment]
@zlianon please open issues in the bug tracker repository.

Sadly we don't support devices, which aren't supported by SODP.

I would google about a solution.

**Comment by Haxk20** [comment]
@MartinX3 Opening an issue in bug tracker is useless as it wont lead anywhere. We just cant support Mediatek. Opening an issue would be just making another issue thats useless.

**Comment by Paulbouchara** [comment]
@zlianon for your information, I saw some device trees for Sony Xperia L1, so that would be a cool base to start off a port work
Note that pretty much all mediatek devices are almost the same so it wouldn't be that hard to do a port for your L3

**Comment by MartinX3** [comment]
@Haxk20 please reread my answer.

**Comment by Haxk20** [comment]
@MartinX3 My bad here. Didnt saw the s in issues.

**Comment by bigrammy** [comment]
I am pretty tired of people blaming MEDIATEK all the time!!
The problems we have is with **Sony NOT** MediaTek. 
There is plenty of MediaTek Sources which are open but Sony add their own stuff which we find hard to overcome. Sony removed MediaTek's SPFlashtool support in favour of Sony's S1 Protocol which has no way to recover the device once soft bricked.
This makes things very difficult since we cannot replace the preloader and or LK. 
Sony should release **open** preloader, lk, logo and secro so we can flash those **without bricking the device**.
Earlier Sony MTK devices used to have "_TEST_" images included in the firmware packages which were flashed on bootloader unlocked devices but these images used to brick the phones just see the "flashtool" threads regarding the C4, M5 and variants of. 
From the XA on these "_TEST_" images were removed and the bricking of MTK's ended.
So ask your OEM's like **Arima** to provide the standard MediaTek or **fully open** Sony ROM's for the **Sony L1** code name _SM31 Pine_ for example. 
Nothing to do with MEDIATEK it's 100% OEM's preventing us doing anything on these cheaper devices hence why we get no OS upgrades on the L devices the L1 released on N and is still on N today Same for the L2 and probably the L3 and L4.
